
country_codes = {
    "USA": "us",
    "Canada": "ca",
    "UK": "gb",
    "India": "in",
    "Australia": "au",
    "Germany": "de",
    "France": "fr",
    "Japan": "jp",
    "China": "cn",
    "Brazil": "br",
    "South Africa": "za",
    "Ukraine": "ua",
    "Albania": "al",
    "Algeria": "dz",
    "Argentina": "ar",
    "Austria": "at",
    "Armenia": "am",
    "Azerbaijan": "az",
    "Belgium": "be",
    "Bosnia and Herzegovina": "ba",
    "Bulgaria": "bg",
    "Bangladesh": "bd",
    "Colombia": "co",
    "Croatia": "hr",
    "Chile": "cl",
    "Cuba": "cu",
    "Cyprus": "cy",
    "Czechia": "cz",
    "Democratic Republic of the Congo": "cd",
    "Denmark": "dk",
    "Ecuador": "ec",
    "Egypt": "eg",
    "Estonia": "ee",
    "Finland": "fi",
    "Georgia": "ge",
    "Greece": "gr",
    "Haiti": "ht",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "Indonesia": "id",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Jamaica": "jm",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "South Korea": "kr",
    "Kosovo": "xk",
    "Latvia": "lv",
    "Liechtenstein": "li",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Malaysia": "my",
    "Malta": "mt",
    "Mexico": "mx",
    "Moldova": "md",
    "Monaco": "mc",
    "Montenegro": "me",
    "Morocco": "ma",
    "Myanmar": "mm",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Nigeria": "ng",
    "North Macedonia": "mk",
    "Norway": "no",
    "Oman": "om",
    "Philippines": "ph",
    "Peru": "pe",
    "Paraguay": "py",
    "Panama": "pa",
    "Pakistan": "pk",
    "Poland": "pl",
    "Portugal": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Romania": "ro",
    "San Marino": "sm",
    "Saudi Arabia": "sa",
    "Scotland, United Kingdom": "gb",
    "Senegal": "sn",
    "Serbia": "rs",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sweden": "se",
    "Switzerland": "ch",
    "Syria": "sy",
    "Taiwan": "tw",
    "Thailand": "th",
    "Tunisia": "tn",
    "Türkiye": "tr",
    "Trinidad and Tobago": "tt",
    "United Arab Emirates": "ae",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Venezuela": "ve",
    "Vietnam": "vn",
    "Wales, United Kingdom": "gb",
    "Bolivia": "bo",
    "Costa Rica": "cr",
    "Guatemala": "gt",
    "Honduras": "hn",
    "El Salvador": "sv",
    "Togo": "tg",
    "Burundi": "bi",
    "Somalia": "so",
    "Iraq": "iq",
    "Benin": "bj",
    "South Sudan": "ss",
    "Yemen": "ye",
    "Rwanda": "rw",
    "Guinea": "gn",
    "Chad": "td",
    "Jordan": "jo",
    "Zimbabwe": "zw",
    "Zambia": "zm",
    "Palestine": "ps",
    "Malawi": "mw",
    "Mali": "ml",
    "Lebanon": "lb",
    "Kuwait": "kw",
    "Cameroon": "cm",
    "Bahrain": "bh",
    "Angola": "ao",
    "Sudan": "sd",
    "Madagascar": "mg",
    "Iran": "ir",
    "Ivory Coast": "ci",
    "Ethiopia": "et",
    "Mozambique": "mz",
    "Tanzania": "tz",
    "Uganda": "ug",
    "Ghana": "gh",
    "Burkina Faso": "bf",
    "Libya": "ly",
    "Sierra Leone": "sl",
    "Central African Republic": "cf",
    "Eritrea": "er",
    "Liberia": "lr",
    "Mauritania": "mr",
    "Gabon": "ga",
    "Namibia": "na",
    "Botswana": "bw",
    "Lesotho": "ls",
    "Equatorial Guinea": "gq",
    "Gambia": "gm",
    "Guinea-Bissau": "gw",
    "Mauritius": "mu",
    "Swaziland": "sz",
    "Djibouti": "dj",
    "Comoros": "km",
    "Cape Verde": "cv",
    "São Tomé and Príncipe": "st",
    "Seychelles": "sc",
    "Aland Islands": "ax",
    "Faroe Islands": "fo",
    "Greenland": "gl",
}