def find_matching_industry(industry):
    AccomList = [
        "Food",
        "Production",
        "Restaurants",
        "Food and Beverage Services",
        "Mobile Food Services",
        "Food, Beverages & Tobacco",
        "Fast food restaurants",
        "Catering services",
        "Bars and nightclubs",
        "Coffee and snack shops",
    ]
    AdvertList = [
        "Advertising/Marketing",
        "Marketing",
        "Advertising",
        "Communications",
        "Marketing & Advertising",
        "Marketing and Advertising",
        "Public Relations & Communications",
        "Public Relations and Communications",
        "Advertising Services",
        "Public Relations and Communications Services",
        "Marketing Services",
        "Advertising / Marketing",
        "Advertising & Marketing",
    ]
    AeroList = [
        "Space",
        "Aviation",
        "Airlines",
        "Aerospace",
        "Defense & Space",
        "Aerospace Defense",
        "Airlines/Aviation",
        "Aviation & Aerospace",
        "Airlines and Aviation",
        "Aviation and Aerospace",
        "Space Research and Technology",
        "Airlines, Airports & Air Services",
        "Aerospace & Defense",
        "Aviation and aerospace industry",
        "Aircraft Parts Distributors",
        "Defense and Space Manufacturing",
        "Aviation and Aerospace Component Manufacturing",
    ]
    AgriList = [
        "Fishery",
        "Farming",
        "Ranching",
        "Forestry",
        "Fishing and Hunting",
        "Fisheries",
        "Forestry and Logging",
        "Horticulture",
        "Agriculture",
        "Agriculture General",
        "Beef Cattle Production",
        "Beekeeping",
        "Plant & Flower Growing",
        "Timber Services",
        "Tobacco Growing",
        "Hunting & Trapping",
        "Forestry & Forest Products",
        "Crops",
        "Ranching and Fisheries",
        "Animals & Livestock",
    ]
    AutoList = [
        "Automotive",
        "Automotive Service & Collision Repair",
        "Motor Vehicles",
        "Motor Vehicle Dealers",
        "Truck Repair",
        "Motor Vehicle Manufacturing",
        "Motor Vehicle Parts Manufacturing",
        "Motor Vehicle Parts",
        "Retail Motor Vehicles",
    ]
    BioList = [
        "Biotechnology",
        "Pharmaceuticals",
        "Biotechnology Research",
        "Pharmaceutical Manufacturing",
        "Drug Manufacturing & Research",
    ]
    CommList = [
        "Translation",
        "Investigations",
        "Environmental Services",
        "Security & Investigations",
        "Translation & Localization",
        "Translation and Localization",
        "Fire Protection",
        "Engineering Services",
        "Landscaping Services",
        "Investment Advice",
        "Surveying and Mapping Services",
        "Information & Document Management",
        "Consumer Goods Rental",
    ]
    CaTList = [
        "Software",
        "Internet",
        "Computer",
        "Nanotechnology",
        "Computer Games",
        "Graphic Design",
        "Network Security",
        "Computer Hardware",
        "Computer Software",
        "Program Development",
        "Computer Networking",
        "Consumer Electronics",
        "Software Application",
        "Information Services",
        "Information Technology",
        "Computers and Technology",
        "Computer & Network Security",
        "Information Technology & Services",
        "Information Technology and Services",
        "Computer and Network Security",
        "IT Services and IT Consulting",
        "Software Development",
        "Mobile Gaming Apps",
        "Nanotechnology Research",
        "Technology and Information",
        "Computer Networking Products",
        "Embedded Software Products",
        "Internet Marketplace Platforms",
        "Data Infrastructure and Analytics",
        "Social Networking Platforms",
        "Data Security Software Products",
        "Security Systems Services",
        "IT System Custom Software Development",
        "Technology, Information and Internet",
        "Business Intelligence Platforms",
        "Mobile Computing Software Products",
        "Desktop Computing Software Products",
        "IT System Operations and Maintenance",
        "Blockchain Services",
        "Business Intelligence (BI) Software",
        "Software General",
        "Financial Software",
        "Software & Technical Consulting",
        "Software Development & Design",
        "Security software",
        "IT System Design Services",
        "Internet Service Providers, Website Hosting & Internet-related Services",
        "Enterprise Resource Planning (ERP) Software",
        "Computer Networking Equipment",
        "Content & Collaboration Software",
        "Healthcare Software",
        "Database & File Management Software",
        "Robotics Engineering",
        "IT System Data Services",
        "Information Collection & Delivery",
        "Networking Software",
        "Engineering Software",
        "Storage & System Management Software",
        "IT System Testing and Evaluation",
        "Customer Relationship Management (CRM) Software",
        "Search Engines & Internet Portals",
        "Artificial Intelligence (AI)",
    ]
    ConstList = [
        "Design",
        "Building",
        "Materials",
        "Shipbuilding",
        "Construction",
        "Architecture",
        "Arts & Crafts",
        "Arts and Crafts",
        "Civil Engineering",
        "Architecture & Planning",
        "Diversified construction",
        "Ship Building/Shipbuilding",
        "Design Services",
        "Architecture and Planning",
        "Nonresidential Building Construction",
        "Residential Building Construction",
        "Building Equipment Contractors",
        "Architecture, Engineering & Design",
        "Commercial & Residential Construction",
        "Apartment & Condominium Construction",
        "Heavy Engineering Construction",
        "Interior Design",
        "Building Structure and Exterior Contractors",
        "Construction General",
        "Building Construction",
    ]
    CorpSList = [
        "Printing",
        "Think Tanks",
        "Market Research",
        "Events Services",
        "Human Resources",
        "Executive Office",
        "Writing and Editing",
        "Facilities Services",
        "Professional Services",
        "Management Consulting",
        "Staffing & Recruiting",
        "Outsourcing/Offshoring",
        "Staffing and Recruiting",
        "Business Consulting and Services",
        "Printing Services",
        "Outsourcing and Offshoring Consulting",
        "Business Skills Training",
        "Human Resources Services",
        "Strategic Management Services",
        "Business Services",
        "Janitorial Services",
        "Business Services General",
        "Administrative and Support Services",
        "Human Resources & Staffing",
        "Business Content",
        "Call Centers & Business Centers",
        "Auctions",
        "Executive Search Services",
        "Holding Companies & Conglomerates",
        "Industry Associations",
    ]
    EduList = [
        "Education",
        "E-Learning",
        "E-learning",
        "Higher Education",
        "Education Management",
        "Primary/Secondary Education",
        "Professional Training & Coaching",
        "E-Learning Providers",
        "E-learning Providers",
        "Education Administration Programs",
        "Primary and Secondary Education",
        "Technical and Vocational Training",
        "Language Schools",
        "Colleges & Universities",
        "Business Certification & IT Schools",
        "Business Coaching",
        "Community Colleges",
        "Educational Services",
        "Fine Arts Schools",
        "For-Profit Universities",
        "Language Instruction",
        "Private Schools",
        "Public Schools",
        "Sports Coaching",
        "Testing & Educational Support",
        "Trade & Technical Schools",
        "Tutoring & Driving Schools",
        "Education General",
        "Training",
        "K-12 Schools",
        "Flight Training",
        "Professional Training and Coaching",
    ]
    FinList = [
        "Banks",
        "Finance",
        "Banking",
        "Accounting",
        "Banks—Regional",
        "Capital Markets",
        "Credit Services",
        "Asset Management",
        "Financial Services",
        "Investment Banking",
        "Investment Management",
        "Financial Conglomerates",
        "Asset and investment management",
        "Financial Data & Stock Exchanges",
        "Venture Capital & Private Equity",
        "Venture Capital and Private Equity Principals",
        "Payments",
        "Cryptocurrency",
        "Funds and Trusts",
        "Accounting & Accounting Services",
        "Credit Cards & Transaction Processing",
        "Commercial Banking",
        "Portfolio Management & Investment Advice",
        "Private Equity, Hedge Funds & Investment Vehicles",
        "Finance General",
        "Commercial and Industrial Equipment Rental",
        "Brokerage",
        "Loan Brokers",
        "cash",
        "Holding Companies",
    ]
    GovList = [
        "Military",
        "Libraries",
        "Public Policy",
        "Public Safety",
        "Law Enforcement",
        "Government Agency",
        "Government Relations",
        "International Affairs",
        "Museums & Institutions",
        "Museums and Institutions",
        "Government Administration",
        "Civic & Social Organization",
        "Executive Offices",
        "Armed Forces",
        "Public Policy Offices",
        "Government Relations Services",
        "Museums, Historical Sites, and Zoos",
        "Community Development and Urban Planning",
        "Housing and Community Development",
        "Correctional Institutions",
        "Government",
        "Museums",
        "Cities, Towns & Municipalities",
        "Utilities Administration",
        "Cities, Towns & Municipalities General",
        "Zoos and Botanical Gardens",
        "Zoos & National Parks",
        "Welfare Service",
        "Economic Programs",
    ]
    HealthList = [
        "Healthcare/Medical",
        "Healthcare / Medical",
        "Health",
        "Veterinary",
        "Medical Device",
        "Medical Devices",
        "Medical Practice",
        "Mental Health Care",
        "Alternative Medicine",
        "Hospital & Health Care",
        "Health, Wellness & Fitness",
        "Health Wellness and Fitness",
        "Recreational Facilities and Services",
        "Wellness and Fitness Services",
        "Hospitals and Health Care",
        "Veterinary Services",
        "Medical Practices",
        "Home Health Care Services",
        "Barber Shops & Beauty Salons",
        "Pet Services",
        "Physical, Occupational and Speech Therapists",
        "Hospitals & Clinics",
        "Public Health",
        "Healthcare",
        "Medical and Diagnostic Laboratories",
        "Health and Human Services",
        "Medical Testing & Clinical Laboratories",
        "Medical Devices & Equipment",
        "Chiropractors",
        "Vocational Rehabilitation Services",
        "Dentists",
        "Healthcare General",
        "Ambulance Services",
        "Nursing Homes and Residential Care Facilities",
        "Child Day Care Services",
    ]
    MachList = [
        "Machinery",
        "Chemicals",
        "Industrial Machinery",
        "Industrial Automation",
        "Mechanical Or Industrial Engineering",
        "Commercial and Industrial Machinery Maintenance",
        "Chemicals, Petrochemicals, Glass & Gases",
        "Industrial Machinery & Equipment",
        "Acetylene Production",
        "Air & Gas Compressor Manufacturing",
    ]
    InsList = [
        "Insurance",
        "Insurance Brokers",
        "Life & Health Insurance",
        "Insurance and Employee Benefit Funds",
        "Insurance Agencies and Brokerages",
        "Insurance Carriers",
        "Claims Adjusting, Actuarial Services",
    ]
    LegalList = [
        "Judiciary",
        "Law Practice",
        "Legal Services",
        "Legislative Office",
        "Security & Investigations",
        "Security and Investigations",
        "Alternative Dispute Resolution",
        "Administration of Justice",
        "Legislative Offices",
        "Law Firms & Legal Services",
    ]
    ManList = [
        "Dairy",
        "Tobacco",
        "Textiles",
        "Plastics",
        "Furniture",
        "Cosmetics",
        "Manufacturing",
        "Wine & Spirits",
        "Semiconductors",
        "Food Production",
        "Polymer industry",
        "Food & Beverages",
        "Wine and Spirits",
        "Building Materials",
        "Railroad Manufacture",
        "Packaging & Containers",
        "Paper & Forest Products",
        "Packaging and Containers",
        "Glass Ceramics & Concrete",
        "Glass, Ceramics & Concrete",
        "Miscellaneous Manufacturing",
        "Consumer Products Manufacturing",
        "Healthcare Product Manufacturing",
        "Electrical/Electronic Manufacturing",
        "Electrical & Electronic Manufacturing",
        "Appliances, Electrical, and Electronics Manufacturing",
        "Packaging and Containers Manufacturing",
        "Paper and Forest Product Manufacturing",
        "Medical Equipment Manufacturing",
        "Sporting Goods Manufacturing",
        "Computer Hardware Manufacturing",
        "Furniture and Home Furnishings Manufacturing",
        "Beverage Manufacturing",
        "Personal Care Product Manufacturing",
        "Dairy Product Manufacturing",
        "Textile Manufacturing",
        "Transportation Equipment Manufacturing",
        "Glass, Ceramics and Concrete Manufacturing",
        "Tobacco Manufacturing",
        "Semiconductor Manufacturing",
        "Component Manufacturing",
        "Railroad Equipment Manufacturing",
        "Plastics Manufacturing",
        "Computers and Electronics Manufacturing",
        "Primary Metal Manufacturing",
        "Food and Beverage Manufacturing",
        "Industrial Machinery Manufacturing",
        "Renewable Energy Semiconductor Manufacturing",
        "Fabricated Metal Products",
        "Measuring and Control Instrument Manufacturing",
        "Animal Feed Manufacturing",
        "Office Furniture and Fixtures Manufacturing",
        "Chemical Manufacturing",
        "Automation Machinery Manufacturing",
        "Electrical Equipment Manufacturing",
        "Communications Equipment Manufacturing",
        "Metal Treatments",
        "Wineries",
        "Electric Lighting Equipment Manufacturing",
        "Sugar and Confectionery Product Manufacturing",
        "HVAC and Refrigeration Equipment Manufacturing",
        "Paint, Coating, and Adhesive Manufacturing",
        "Glass Product Manufacturing",
        "Metalworking Machinery Manufacturing",
        "Manufacturing General",
        "Electronics",
        "Wood Product Manufacturing",
        "Boats & Submarines",
        "Toys & Games",
        "Renewable Energy Equipment Manufacturing",
        "Machinery Manufacturing",
        "Textiles & Apparel",
        "Engines and Power Transmission Equipment Manufacturing",
        "Plastic, Packaging & Containers",
        "Pulp & Paper",
        "Audio and Video Equipment Manufacturing",
        "Test & Measurement Equipment",
        "Telecommunication Equipment",
        "Hand, Power and Lawn-care Tools",
        "Climate Technology Product Manufacturing",
        "Commercial and Service Industry Machinery Manufacturing",
        "Plastics and Rubber Product Manufacturing",
        "Agricultural Chemical Manufacturing",
        "Chemical Raw Materials Manufacturing",
        "Seafood Product Manufacturing",
        "Architectural and Structural Metal Manufacturing",
        "Robot Manufacturing",
        "Tires & Rubber",
        "Rubber Products Manufacturing",
        "Manufacturing of agricultural machinery & equipment",
        "Fashion Accessories Manufacturing",
        "Construction Hardware Manufacturing",
        "Glass & Clay",
    ]
    MediaList = [
        "Music",
        "Internet",
        "Animation",
        "Publishing",
        "Newspapers",
        "Photography",
        "Online Media",
        "TV and Radio",
        "Performing Arts",
        "Broadcast Media",
        "Media Production",
        "Motion Pictures and Film",
        "Motion Pictures & Film",
        "Internet Publishing",
        "Online Audio and Video Media",
        "Broadcast Media Production and Distribution",
        "Book and Periodical Publishing",
        "Movies and Sound Recording",
        "Technology, Information and Media",
        "Newspaper Publishing",
        "Book Publishing",
        "Animation and Post-production",
        "Movies, Videos, and Sound",
        "Internet News",
        "Media & Internet",
        "Broadcasting",
        "Multimedia, Games and Graphics Software",
        "Photography Studio",
        "Media & Internet General",
        "Radio and Television Broadcasting",
        "Newspapers & News Services",
    ]
    MinList = [
        "Mining & Metals",
        "Mining",
        "Metals & Mining General",
        "Coal Mining",
        "Copper, Nickel, Lead & Zinc Mining",
        "Gold & Silver Ore Mining",
        "Metal Ore Mining",
    ]
    NonPList = [
        "Fundraising",
        "Philanthropy",
        "Political Organization",
        "Religious Institutions",
        "Individual & Family Services",
        "Civil and public organizations",
        "Non-profit Organization Management",
        "Civic and Social Organizations",
        "Individual and Family Services",
        "Philanthropic Fundraising Services",
        "Non-profit Organizations",
        "Political Organizations",
        "Religious Organizations",
        "Membership Organizations",
        "Fund-Raising",
        "Professional Organizations",
        "Organizations",
        "Charitable Organizations & Foundations",
        "Organizations General",
    ]
    RealEList = [
        "Real Estate",
        "The property",
        "Commercial Real Estate",
        "Leasing Real Estate",
        "Leasing Non-residential Real Estate",
        "Leasing Residential Real Estate",
        "Real Estate and Equipment Rental Services",
        "Apartment Rental",
    ]
    ResList = [
        "Research",
        "Research Services",
        "Scientific Research & Development",
    ]
    RetailList = [
        "Retail",
        "Wholesale",
        "Supermarkets",
        "Consumer Good",
        "Consumer Goods",
        "Sporting Goods",
        "Food & Beverages",
        "Specialty Retail",
        "Apparel & Fashion",
        "Luxury Goods & Jewelry",
        "Business Supplies & Equipment",
        "Business Supplies and Equipment",
        "Perfumery and cosmetic industry",
        "International Trade & Development",
        "International Trade and Development",
        "Retail Office Equipment",
        "Wholesale Building Materials",
        "Retail Apparel and Fashion",
        "Retail Luxury Goods and Jewelry",
        "Retail Groceries",
        "Retail Health and Personal Care Products",
        "Retail Art Supplies",
        "Online and Mail Order Retail",
        "Wholesale Import and Export",
        "Wholesale Alcoholic Beverages",
        "Wholesale Food and Beverage",
        "Wholesale Metals and Minerals",
        "Flowers, Gifts & Specialty Stores",
        "Retail Building Materials and Garden Equipment",
        "Wholesale Petroleum and Petroleum Products",
        "Wholesale Appliances, Electrical, and Electronics",
        "Wholesale Motor Vehicles and Parts",
        "Wholesale Chemical and Allied Products",
        "Home Improvement & Hardware Retail",
        "Specialty Trade Contractors",
        "Consumer Electronics & Computers Retail",
        "Department Stores, Shopping Centers & Superstores",
        "Record, Video & Book Stores",
        "Sporting & Recreational Equipment Retail",
        "Retail Furniture and Home Furnishings",
        "Apparel & Accessories Retail",
        "Pet Products",
        "Retail General",
        "Retail Musical Instruments",
        "Grocery Retail",
        "Gas Stations, Convenience & Liquor Stores",
        "Drug Stores & Pharmacies",
        "Bicycle Dealership and Repair",
        "Vitamins, Supplements & Health Stores",
        "Automobile Parts Stores",
        "Other Rental Stores (Furniture, A/V, Construction & Industrial Equipment)",
        "Jewelry & Watch Retail",
        "Office Products Retail & Distribution",
        "Retail Books and Printed News",
        "Food and Beverage Retail",
        "Retail Pharmacies",
        "Wholesale Drugs and Sundries",
        "Cosmetics, Beauty Supply & Personal Care Products",
        "Wholesale Machinery",
        "Agricultural Machinery Wholesaling",
        "Retail Art Dealers",
        "Household Goods",
    ]
    SerList = [
        "Consumer Services",
        "Environmental Services",
        "Maintenance of office and industrial equipment",
        "Equipment Rental Services",
        "Electronic and Precision Equipment Maintenance",
        "Vehicle Repair and Maintenance",
        "Commercial and Industrial Equipment Rental",
        "Services for the Elderly and Disabled",
        "Consumer Services General",
        "Facilities Management & Commercial Cleaning",
        "Laundry & Dry Cleaning Services",
        "Hair Salons",
        "Elevator Installation & Service",
        "Software Development",
        "Car & Truck Rental",
        "Security Products & Services",
    ]
    TelList = [
        "Telecom",
        "Internet",
        "Wireless",
        "Telecommunications",
        "Wireless Services",
        "Satellite Telecommunications",
        "Cable & Satellite",
        "Telecommunications General",
        "Telephony & Wireless",
        "Media and Telecommunications",
    ]
    TransList = [
        "Trucking",
        "Maritime",
        "Railroads",
        "Warehousing",
        "Taxi Service",
        "Import & Export",
        "Import and Export",
        "Road and rail transport",
        "Logistics & Supply Chain",
        "Logistics and Supply Chain",
        "Integrated Freight & Logistics",
        "Transportation/Trucking/Railroad",
        "Transportation, Logistics and Storage",
        "Truck Transportation",
        "Maritime Transportation",
        "Warehousing and Storage",
        "Rail Transportation",
        "Ground Passenger Transportation",
        "Transportation, Logistics, Supply Chain and Storage",
        "Urban Transit Services",
        "Freight and Package Transportation",
        "Pipeline Transportation",
        "Transportation Programs",
        "Transportation",
        "Rail, Bus & Taxi,",
        "Transportation General",
        "Freight & Logistics Services",
        "Package/Freight Delivery",
        "Marine Shipping & Transportation",
        "Postal Services",
        "Taxi and Limousine Services",
        "Trucking, Moving & Storage",
        "Interurban and Rural Bus Services",
    ]
    TravList = [
        "Music",
        "Sports",
        "Hospitality",
        "Entertainment",
        "Gambling & Casinos",
        "Leisure Travel & Tourism",
        "Leisure, Travel & Tourism",
        "Entertainment Providers",
        "Gambling Facilities and Casinos",
        "Musicians",
        "Spectator Sports",
        "Travel Arrangements",
        "Artists and Writers",
        "Amusement Parks and Arcades",
        "Golf Courses and Country Clubs",
        "Recreational Facilities",
        "Sports Teams and Clubs",
        "Hotels and Motels",
        "Sports and Recreation Instruction",
        "Fine Art",
        "Hospitality General",
        "Gambling & Gaming",
        "Lodging & Resorts",
        "Travel Agencies & Services",
        "Amusement Parks, Arcades & Attractions",
        "Festivals and Events",
        "Concert & Event Promotion",
        "Golf Courses & Country Clubs",
        "Gym, Health & Fitness Clubs",
        "Musical Groups & Artists",
        "Arts, Entertainment and Recreation",
        "Amusement Parks",
        "Golf Driving Ranges & Family Fun Centers",
        "Fitness & Dance Facilities",
        "Performing Arts and Spectator Sports",
        "Skiing Facilities",
    ]
    UtilList = [
        "Utilities",
        "Oil & Energy",
        "Waste Management",
        "Renewables & Environment",
        "Energy, Utilities & Waste Treatment",
        "Oil and Gas",
        "Waste Treatment and Disposal",
        "Solar Electric Power Generation",
        "Electric Power Generation",
        "Wind Electric Power Generation",
        "Water Supply and Irrigation Systems",
        "Electric Power Transmission, Control, and Distribution",
        "Air, Water, and Waste Program Management",
        "Nuclear Electric Power Generation",
        "Renewable Energy Power Generation",
        "Electricity",
        "Waste Collection",
        "Oil, Gas, and Mining",
        "Services for Renewable Energy",
        "Biomass Electric Power Generation",
        "Oil & Gas Exploration & Services",
        "Electricity, Oil & Gas",
        "Natural Gas Distribution",
        "Nuclear Power",
        "Sewage Treatment Facilities",
        "Solar Power",
        "Hydroelectric Power",
        "Electric Power Transmission",
        "Coal & Natural Gas Power",
        "Water Supply & Irrigation Systems",
        "Steam & Air-Conditioning Supply",
        "Waste Treatment, Environmental Services & Recycling",
        "Energy, Utilities & Waste Treatment General",
        "Hydroelectric Power Generation",
        "Water & Water Treatment",
        "Water, Waste, Steam, and Air Conditioning Services",
    ]

    lists = {
        "Accommodation and Food Services": AccomList,
        "Advertising / Marketing": AdvertList,
        "Aerospace / Aviation": AeroList,
        "Agriculture": AgriList,
        "Automotive": AutoList,
        "Biotech and Pharmaceuticals": BioList,
        "Commercial Services": CommList,
        "Computers and Technology": CaTList,
        "Construction": ConstList,
        "Corporate Services": CorpSList,
        "Education": EduList,
        "Finance": FinList,
        "Government": GovList,
        "Healthcare / Medical": HealthList,
        "Industrial Machinery, Gas and Chemicals": MachList,
        "Insurance": InsList,
        "Legal": LegalList,
        "Manufacturing": ManList,
        "Media": MediaList,
        "Mining": MinList,
        "Non-Profit / Organizations": NonPList,
        "Real Estate": RealEList,
        "Research": ResList,
        "Retail and Consumer Goods": RetailList,
        "Service Industry": SerList,
        "Telecommunications": TelList,
        "Transportation and Logistics": TransList,
        "Travel / Hospitality / Entertainment": TravList,
        "Utility / Energy": UtilList,
    }

    for key, value_list in lists.items():
        if industry in value_list:
            return key

    return "Unknown"
