INDUSTRIES = [
    'Accommodation and Food Services', 
    'Advertising / Marketing', 
    'Aerospace / Aviation', 
    'Agriculture',
    'Automotive', 
    'Biotech and Pharmaceuticals', 
    'Commercial Services', 
    'Computers and Technology', 
    'Construction', 
    'Corporate Services', 
    'Education', 
    'Finance', 
    'Government', 
    'Healthcare / Medical', 
    'Industrial Machinery, Gas and Chemicals', 
    'Insurance', 
    'Legal', 
    'Manufacturing', 
    'Media',
    'Mining', 
    'Non-Profit / Organizations', 
    'Real Estate', 
    'Research', 
    'Retail and Consumer Goods',
    'Service Industry', 
    'Telecommunications', 
    'Transportation and Logistics', 
    'Travel / Hospitality / Entertainment', 
    'Utility / Energy'
]